#!/bin/bash
videos=(
"d5kReZhI7y0|01_Compte_SkyDreamSoft"
"-DdKcyj2Rzs|02_Dossier_de_vol"
"Kvu3udoOp9E|03_Scratch_Pad"
"DPel0USDr1U|04_Notams_graphiques"
"aEebE7V95Ak|05_Barre_superieure"
"qaU-S1Ie1CI|06_Ouvrir_PDF_Android"
"Eog2pOmTPNg|07_Tour_horizon"
"PLK2H5Wgra4|08_Gestion_regions"
"sG-hKathO0c|09_Document_Management"
"ATVYwyCVWP0|10_Gestion_donnees"
"7aXPhnJoLdk|11_Gestion_appareils"
"DBpg-528GTI|12_Metar_Taf_Sigmet_Wintem"
"0V2TcdvezPE|13_Cartes_meteo"
"cpN4zFha8xo|14_Radar_meteo"
"NPpOz2QoQAU|15_Carte_vectorielle"
"0bhb7_Kw7tM|16_Double_tap"
"gxn-wJreOow|17_Chronometres"
"GK0HQRX5S1Y|18_VAC_georeferencees"
"uLL34-HW6cs|19_My_first_navigation"
"SD8dcfpadGI|20_Mode_hybride"
"v0DZfFlCQaU|21_Fonction_Direct"
"JWLg73giPmQ|22_Informations_terrain"
"RilDrWjlguo|23_Mode_carte_automatique"
"6dB28voZksg|24_Cartes_en_ligne"
"CCDwFP4t9oc|25_Temporary_Zones_Auto"
"EqbOUKXeoQY|26_Temporary_Zones_Manual"
"bXg575c_Enw|27_Flight_tracking_general"
"-S3SoU66FNY|28_Suivi_vol_point_courant"
"HfrN1wpN74E|29_Suivi_vol_barre_inferieure"
"BPaK71fnur0|30_Suivi_vol_profil_dynamique"
"F-E6ha58Z5c|31_Connexion_simulateur"
"w7eOm3l8v4Y|32_Trace_live"
"pux80Scm5uU|33_Traces_enregistrees"
"LaeT193P_YI|34_Log_navigation"
"Dh0QeSm9utY|35_Navigation_profile"
"9VFfay-Wt1U|36_Devis_carburant"
"sZP_0QUSWUY|37_Mass_Centering"
"5397ioPcp1k|38_Terrains_sur_route"
"LtbkUsFacnY|39_Notams_de_route"
"KoAwWZjVOM8|40_Importation_navigations"
"SE0pmn-9n-U|41_Custom_Points_Part1"
"5G2couFR4U0|42_Points_personnalises_Part2"
"f7FvQpWBIhk|43_Documents_personnels"
"Ho9xmRMFx3Q|44_Surcouches_personnelles"
"8B5zkZIzK9Q|45_Cartes_personnalisees"
"0-cStHF6P2g|46_Detection_trafics_Stratux"
"jjhPh_TtRC8|47_Detection_trafics_SafeSky"
)

for entry in "${videos[@]}"; do
  IFS='|' read -r vid name <<< "$entry"
  echo "Downloading: $name ($vid)"
  yt-dlp --write-auto-sub --sub-lang fr --skip-download --sub-format vtt \
    -o "$name" "https://www.youtube.com/watch?v=$vid" 2>&1 | grep -E "(Writing|ERROR)"
done
echo "DONE"
